# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('detailAddress', models.CharField(max_length=200)),
                ('fullAddress', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='AxfUser',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=500, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('cartNum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'axfusers',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('isChoice', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sort', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sort', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Category')),
            ],
            options={
                'db_table': 'childs',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('flag', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastTime', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.AxfUser')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Order')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longName', models.CharField(max_length=40)),
                ('productId', models.CharField(max_length=20)),
                ('storeNums', models.IntegerField()),
                ('specifics', models.CharField(max_length=20)),
                ('sort', models.IntegerField()),
                ('marketPrice', models.FloatField()),
                ('price', models.FloatField()),
                ('img', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=40)),
                ('brandId', models.CharField(max_length=20)),
                ('brandName', models.CharField(max_length=40)),
                ('safeDay', models.CharField(max_length=20)),
                ('safeUnit', models.CharField(max_length=20)),
                ('safeUnitDesc', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Category')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Child')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.AxfUser'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.AxfUser'),
        ),
    ]
